# Generated by Django 3.0 on 2023-04-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image_film',
            field=models.ImageField(blank=True, upload_to='films/', verbose_name='Image'),
        ),
    ]
